"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:deep_blue fg:surface0)\
$directory\
[](fg:deep_blue bg:midnight_blue)\
$git_branch\
$git_status\
[](fg:midnight_blue bg:blue_sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue_sapphire bg:azure)\
$docker_context\
[](fg:azure bg:indigo)\
$time\
[ ](fg:indigo)\
$line_break$character"""

palette = 'deep_blue_mocha'

[palettes.deep_blue_mocha]
# Gedeckte Blau-Töne und entspannte Farben für weniger Kontrast
rosewater = "#b3c1d1"  # Sanftes, entspanntes Blau
flamingo = "#8fa3b2"
pink = "#7f9cb0"
orange = "#6b8a99"
red = "#9c7385"
maroon = "#8c5e6a"
deep_blue = "#2c3e52"  # Dunkles Blau als Grundfarbe
midnight_blue = "#3e4a5b"
blue_sapphire = "#40628d"
blue = "#2f4b74"
azure = "#5a81b4"
indigo = "#43588d"
text = "#c4d2e1"
subtext1 = "#a0b1c2"
subtext0 = "#7a8d9f"
overlay2 = "#6a7f89"
overlay1 = "#5a6e78"
overlay0 = "#4b5f69"
surface2 = "#3d4e57"
surface1 = "#2e3d47"
surface0 = "#1f2e39"
base = "#161e29"
mantle = "#0f1521"
crust = "#0a0f18"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CachyOS = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:deep_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol $branch ](fg:base bg:blue_sapphire)]($style)'

[git_status]
style = "bg:midnight_blue"
format = '[[($all_status$ahead_behind )](fg:base bg:blue_sapphire)]($style)'

[nodejs]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[c]
symbol = " "
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[rust]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[golang]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[php]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[java]
symbol = " "
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[haskell]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[python]
symbol = ""
style = "bg:midnight_blue"
format = '[[ $symbol( $version) ](fg:base bg:midnight_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:blue_sapphire bg:surface1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:deep_blue"
format = '[[  $time ](fg:mantle bg:indigo)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:blue)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:blue)'
vimcmd_replace_one_symbol = '[](bold fg:indigo)'
vimcmd_replace_symbol = '[](bold fg:indigo)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
